### ISSUE TITLE
Needs Way Better Hints For Actual Regex Usage, And Chaining Involved For 'count_sentences' Method

### ISSUE THREAD

**Issue by SamuelBanya** [learn-co-curriculum/phase-3-ruby-oo-self-count-sentences-lab#5]
### Canvas Link

https://learning.flatironschool.com/courses/5286/assignments/172609?module_item_id=376666

### Concern

This lab just links to some random page on regex statement.

It should actually hint that the '.', '?', and '!' symbols should be used.

Also, nothing is ever mentioned about chaining which is required in this example.

You can't just require regex for assignments but not actually teach it, let alone make it basic enough for the average person to be able to do this.

This is coming from someone who has had to use complex regex statements in the past for work, and I think its kind of ridiculous that no mention of how to actually use regex is mentioned, yet its flat out required for labs like this.

**Comment by lizbur10** [comment]
Hi @SamuelBanya ,

Thanks again for providing feedback - we will take this into consideration as we work on updating the Phase 3 content.

As always, thanks for contributing! 💙
